name: ClaudeWatch
options:
  bundleIdPrefix: com.claudewatch
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_INJECT_BASE_ENTITLEMENTS: YES

targets:
  ClaudeWatch:
    type: application
    platform: macOS
    sources:
      - path: ClaudeUsageBar
        excludes:
          - "**/*.plist"
    settings:
      base:
        PRODUCT_NAME: "ClaudeWatch"
        PRODUCT_BUNDLE_IDENTIFIER: com.claudewatch.app
        INFOPLIST_FILE: ClaudeUsageBar/Resources/Info.plist
        GENERATE_INFOPLIST_FILE: false
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        CODE_SIGN_ENTITLEMENTS: ""
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
